### ISSUE TITLE
stepIO' and wrap' steps that have sent exceptions just hang the 2nd time

### ISSUE THREAD

**Issue by YPares** [tweag/funflow#132]
Consider the following code:
```
testFail = stepIO'
          (def { cache = defaultCacherWithIdent 4783264871236 }) $
          \_ -> error "stuff"
```

If you run it (with runFlowEx and an sql coordinator), it crashes as expected the first time, but then every subsequent time we run it, instead of always retrying the step it just hangs endlessly. We see the same behaviour in `porcupine` using `wrap'` instead of `stepIO'`.

**Comment by YPares** [comment]
Here's a minimum repro:

```{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE ScopedTypeVariables #-}

import Control.Funflow
import Data.Default

import Path

testFail _ = stepIO'
           (def { cache = defaultCacherWithIdent 4783264871236 }) $
           \(ints::()) -> error "plop" :: IO Int

main :: IO ()
main = withSimpleLocalRunner [absdir|/home/yves/store.ff|] $ \runner -> do
   r <- runner (testFail 0) ()
   print r
```

When running that twice I see:

```
$ stack exec -- example1
Left plop
CallStack (from HasCallStack):
  error, called at examples/Example1.hs:71:27 in main:Main
$ stack exec -- example1
[2018-12-10 17:54:51][FFExecutorD.executeLoop][Info][yves-MacBookPro][25786][ThreadId 4][funflow-1.4.0-1ys8NXK18caC7IITqQsDsS:Control.Funflow.External.Executor src/Control/Funflow/External/Executor.hs:181:9] Initialising connection to coordinator.
^C
```

**Comment by mpickering** [comment]
Is this the same as #116 ? Does it stop hanging if you delete the lock files from the store?

**Comment by YPares** [comment]
@mpickering It might be the same yes. I don't see any `.lock` file but when I removed the `pending-*` folder and relaunch, then it stops hanging, yes

**Comment by regnat** [comment]
I recurrently hit this error too.

Looking at the code, it looks like the cause is in https://github.com/tweag/funflow/blob/master/funflow/src/Control/Funflow/Exec/Simple.hs#L98:
At that point,
- `f` corresponds to the action that the step should run (the interpretation of the effect, or the IO action wrapped into the `stepIO`)
- The path associated to the computation is set as `pending`

It looks like the exceptions raised during the `f -< i` call aren't caught, which means that the store path will be left as `pending`, and next time we run the flow, it will see that the store path is `pending` so wait indefinitely for it to be completed (which will never happen since nothing is running to complete it).

@aherrmann @nc6 does that look plausible to you? In that case I assume it's simply a matter of catching a possible exception and run `removeFailed` like it's done in the `writeStore` function

**Comment by aherrmann** [comment]
@regnat Yes, that looks plausible. To make this fully async exception safe I think we'd need to use `withConstructIfMissing` instead of `constructOrWait`. But this should solve the issue here.

**Comment by YPares** [comment]
@aherrmann isn't using `onException` from `safe-exceptions` enough? It should protect against any exception, right, no only synchronous? (I believe the "safe" part means that async exceptions cannot interrupt the exception handler, which is masked until it finishes)

**Comment by aherrmann** [comment]
@YPares an async exception could strike after [`constructOrWait`](https://github.com/regnat/funflow/commit/31fbdce1766c9607fec9ee19d1ce1c5f10909543#diff-9f6524d131fc21434e1c52e8288e086bR81) has marked the item as `pending`, but before we've entered [`onException`](https://github.com/regnat/funflow/commit/31fbdce1766c9607fec9ee19d1ce1c5f10909543#diff-9f6524d131fc21434e1c52e8288e086bR104).
